**Importing libraries**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


**Load dataset**

In [ ]:
df=pd.read_csv('/content/kc_house_data.csv')

Analyse Dataset

In [ ]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [ ]:
df.shape

(21613, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [ ]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
# Move 'price' column to the end
df = df[[col for col in df.columns if col != 'price'] + ['price']]

# Verify the new column order
print(df.columns)

Index(['id', 'date', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'price'],
      dtype='object')


In [ ]:
df.head()

id             date  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  7129300520  20141013T000000         3       1.00         1180      5650   
1  6414100192  20141209T000000         3       2.25         2570      7242   
2  5631500400  20150225T000000         2       1.00          770     10000   
3  2487200875  20141209T000000         4       3.00         1960      5000   
4  1954400510  20150218T000000         3       2.00         1680      8080   

   floors  waterfront  view  condition  ...  sqft_above  sqft_basement  \
0     1.0           0     0          3  ...        1180              0   
1     2.0           0     0          3  ...        2170            400   
2     1.0           0     0          3  ...         770              0   
3     1.0           0     0          5  ...        1050            910   
4     1.0           0     0          3  ...        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15     price  
0        5650  221900.0  
1        7639  538000.0  
2        8062  180000.0  
3        5000  604000.0  
4        7503  510000.0  

[5 rows x 21 columns]

In [ ]:
df['waterfront'].unique()


array([0, 1])

In [ ]:
x=df.iloc[:,2:-1]

In [ ]:
x

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21608         3       2.50         1530      1131     3.0           0     0   
21609         4       2.50         2310      5813     2.0           0     0   
21610         2       0.75         1020      1350     2.0           0     0   
21611         3       2.50         1600      2388     2.0           0     0   
21612         2       0.75         1020      1076     2.0           0     0   

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0              3      7        1180              0      1955             0   
1              3      7        2170            400      1951          1991   
2              3      6         770              0      1933             0   
3              5      7        1050            910      1965             0   
4              3      8        1680              0      1987             0   
...          ...    ...         ...            ...       ...           ...   
21608          3      8        1530              0      2009             0   
21609          3      8        2310              0      2014             0   
21610          3      7        1020              0      2009             0   
21611          3      8        1600              0      2004             0   
21612          3      7        1020              0      2008             0   

       zipcode      lat     long  sqft_living15  sqft_lot15  
0        98178  47.5112 -122.257           1340        5650  
1        98125  47.7210 -122.319           1690        7639  
2        98028  47.7379 -122.233           2720        8062  
3        98136  47.5208 -122.393           1360        5000  
4        98074  47.6168 -122.045           1800        7503  
...        ...      ...      ...            ...         ...  
21608    98103  47.6993 -122.346           1530        1509  
21609    98146  47.5107 -122.362           1830        7200  
21610    98144  47.5944 -122.299           1020        2007  
21611    98027  47.5345 -122.069           1410        1287  
21612    98144  47.5941 -122.299           1020        1357  

[21613 rows x 18 columns]

In [ ]:
x.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

**separate dependent and independent features**

In [ ]:
X=x.values
X

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [ ]:
y=df.iloc[:,-1].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

Split dataset into X_train,y_train

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

**Scalling data**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

array([[-0.39526335, -0.47445144, -0.32393262, ...,  0.44228847,
         1.12607326,  0.01344043],
       [-1.46896378, -1.45258323, -1.18365301, ..., -0.53995821,
        -1.04652268, -0.28066159],
       [-0.39526335, -1.45258323, -1.09547656, ..., -0.86025604,
        -1.19331971, -0.1789339 ],
       ...,
       [-0.39526335,  0.50368036,  0.05081729, ...,  1.29641601,
        -0.42997519, -0.36604019],
       [-2.54266422, -1.77862716, -1.8670205 , ..., -0.77484328,
        -1.19331971,  0.08265159],
       [ 0.67843709,  0.50368036,  1.16404497, ...,  0.81952813,
         1.52242522, -0.24443927]])

In [ ]:
y_train

array([325000., 257000., 228500., ..., 575000., 245000., 315000.])

In [ ]:
# Scalling y 'target' variable
y_train=sc.fit_transform(y_train.reshape(-1, 1))
y_test=sc.transform(y_test.reshape(-1, 1))

In [ ]:
y_train

array([[-0.58864574],
       [-0.77677507],
       [-0.85562339],
       ...,
       [ 0.10300621],
       [-0.80997436],
       [-0.61631182]])

**Building ANN **

In [ ]:
ann = tf.keras.Sequential()

In [ ]:
# input layer
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))
# 1st hidden layer
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
# 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
# output layer
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


In [ ]:
ann.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.3281 - mae: 0.3448 - val_loss: 0.1676 - val_mae: 0.2585
Epoch 2/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1619 - mae: 0.2459 - val_loss: 0.1519 - val_mae: 0.2384
Epoch 3/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1448 - mae: 0.2323 - val_loss: 0.1363 - val_mae: 0.2269
Epoch 4/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1337 - mae: 0.2220 - val_loss: 0.1339 - val_mae: 0.2241
Epoch 5/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1181 - mae: 0.2104 - val_loss: 0.1264 - val_mae: 0.2102
Epoch 6/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1101 - mae: 0.2049 - val_loss: 0.1195 - val_mae: 0.2043
Epoch 7/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1007 - mae: 0.1958 - val_loss: 0.1534 - val_mae: 0.2211
Epoch 8/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1099 - mae: 0.2047 - val_loss: 0.1222 - val_mae: 0.2061
Epoch 9/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/

In [ ]:
y_pred = ann.predict(X_test)


136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [ ]:
y_pred

array([[-0.47914255],
       [ 0.8220181 ],
       [ 1.4392555 ],
       ...,
       [-0.60778505],
       [ 0.12422486],
       [-0.5573838 ]], dtype=float32)

In [ ]:
y_actual = sc.inverse_transform(y_test)

# Display few examples
for i in range(5):
    print(f"Actual: {y_actual[i][0]:.0f}  |  Predicted: {y_pred[i][0]:.0f}")



Actual: 365000  |  Predicted: 364580
Actual: 865000  |  Predicted: 834889
Actual: 1038000  |  Predicted: 1057992
Actual: 1490000  |  Predicted: 2212779
Actual: 711000  |  Predicted: 727323


In [ ]:
new_data = [[3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639]]
print(ann.predict(sc.transform(new_data)))

ValueError: X has 18 features, but StandardScaler is expecting 1 features as input.

In [ ]:
print(ann.predict(sc.transform([[3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639]])))

ValueError: X has 18 features, but StandardScaler is expecting 1 features as input.

In [ ]:
x.head(2)

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   

   zipcode      lat     long  sqft_living15  sqft_lot15  
0    98178  47.5112 -122.257           1340        5650  
1    98125  47.7210 -122.319           1690        7639